# ASP.NET Core (.NET Framework) 


# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  drop: '$(build.artifactstagingdirectory)/drop'
stages:
  - stage: Build
    jobs:
    - job: Build
      displayName: "Build ClientManagement.Web"
      steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            dotnet tool install -g Microsoft.Web.LibraryManager.Cli
            cd ./Core.Presentation.ViewComponents
            libman restore
      # 2. Build Step (with --no-restore)
      - task: DotNetCoreCLI@2
        displayName: 'Build ClientManagement.Web'
        inputs:
          command: 'publish'
          projects: '**/ClientManagement.Presentation.Web.csproj'
          arguments: '--configuration DevOnline --output $(drop)'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(drop)'
          ArtifactName: 'drop'
         
      

                          
