# ASP.NET Core (.NET Framework) 


# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'windows-latest'

variables:
  - group: dockerCredentials
  - name: solution
    value: '**/*.sln'
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'DevOnline'
  - name: containerRepository
    value: 'tsholofelo768'
  - name: imageTag
    value: 'clientmanagement-presentation-web'
  - name: drop
    value: '$(build.artifactstagingdirectory)/drop'
  - name: projectPath
    value: './ClientManagement.Presentation.Web'


stages:
  - stage: Build
    jobs:
    - job: Build
      displayName: "Build ClientManagement.Web"
      steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            dotnet tool install -g Microsoft.Web.LibraryManager.Cli
            cd ./Core.Presentation.ViewComponents
            libman restore
            cd ..
            dotnet workload restore
            
      # 2. Build Step (with --no-restore)
      # - task: DotNetCoreCLI@2
      #   displayName: 'Build ClientManagement.Web'
      #   inputs:
      #     command: 'publish'
      #     projects: '**/ClientManagement.Presentation.Web.csproj'
      #     arguments: ''
      - task: DotNetCoreCLI@2
        inputs:
          command: 'publish'
          publishWebProjects: false
          arguments: '--configuration $(buildConfiguration) --output $(drop)'
          zipAfterPublish: false
          modifyOutputPath: false
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(drop)'
          ArtifactName: 'drop'
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            docker login -u $(registryUserName) -p $(registryPassword)
            cd $(projectPath)
            dotnet publish --os linux --arch x64 -t:PublishContainer -p:ContainerRepository=$(containerRepository) -p:ContainerImageTags=$(imageTag)
            cd ../


            
         
         
      
          

      
         
      

                          
