# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://microsoft.com

pool:
  vmImage: 'windows-latest'

variables:
  - group: dockerCredentials
  - name: solution
    value: '**/*.sln'
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'DevOnline'
  - name: containerRepository
    value: 'tsholofelo768/clientmanagement-presentation-web'
  - name: imageTag
    value: '$(build.buildId)'
  - name: drop
    value: '$(build.artifactstagingdirectory)/drop'
  - name: projectPath
    value: 'ClientManagement.Presentation.Web/ClientManagement.Presentation.Web.csproj'
  - name: projectDir
    value: ClientManagement.Presentation.Web

stages:
  - stage: Build
    jobs:
      - job: Build
        displayName: "Build ClientManagement.Web"
        steps:
          # 1. Restore client-side libraries and workloads
          - task: Bash@3
            displayName: 'Restore Libman & Workloads'
            inputs:
              targetType: 'inline'
              script: |
                dotnet tool install -g Microsoft.Web.LibraryManager.Cli
                cd ./Core.Presentation.ViewComponents
                libman restore
                cd ..
                dotnet workload restore

          # 2. Publish Web Files to Drop (for traditional deployment)
          # - task: DotNetCoreCLI@2
          #   displayName: 'Publish Web Files to Drop'
          #   inputs:
          #     command: 'publish'
          #     publishWebProjects: false
          #     projects: '$(projectPath)' # Fixed: Explicit direct path
          #     arguments: '--configuration $(buildConfiguration) --output $(drop)'
          #     zipAfterPublish: false
          #     modifyOutputPath: false

          # 3. Save traditional build artifacts
          # - task: PublishBuildArtifacts@1
          #   displayName: 'Publish Drop Artifacts'
          #   inputs:
          #     PathtoPublish: '$(drop)'
          #     ArtifactName: 'drop'

          - task: Bash@3
            displayName: 'Restore Workloads and publish container'
            inputs:
              targetType: 'inline'
              script: |
                dotnet workload restore
                cd $(projectDir)
                docker login -u $(registryUserName) -p $(registryPassword)
                dotnet publish --configuration $(buildConfiguration) --os linux --arch x64 -t:PublishContainer -p:ContainerRepository=$(containerRepository) -p:ContainerImageTags=v$(imageTag) -p:ContainerRegistry=index.docker.io 
                docker push $(containerRepository):v$(imageTag)
                docker image list
          # 4. Containerize and Push Directly via native .NET CLI
       
