apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.appConfigName}}
  namespace: {{.Values.namespace}}
data:
 appsettings.json: |
  {
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "AllowedHosts": "*",
  "ConnectionStrings": {
    "Default": "Initial Catalog=rswyrbgd_izybill;Server=148.251.89.211;Trust Server Certificate=True;User ID=rswyrbgd_izybill;Password=&cx3!N6fojZ0qJbg;"
  },
  "ApiBaseUrl": "https://izybill-dev.bakgatlasolutions.com",
  "EmailSettings": {
    "Smtp": "smtp.gmail.com",
    "SendFrom": "izybill85@gmail.com",
    "Password": "owuj gxtw ycfz xxwj",
    "Port": 587
  },
  "AppInfo": {
    "Version": "0.3.1",
    "Name": "IzyBill",
    "PoweredBy": "Growthlytix"
  },
  "Pagination": {
    "PageSize": 10
  },
  "AdminAccount": {
    "Username": "izybill",
    "Password": "izybill@777"
  },
  "AI": {
    "SkillPath": "Agents/Skills",
    "OllamaUrl": "http://localhost:11434",
    "VectorStoreUrl": "http://localhost:6334",
    "VectorStoreCollectionName": "Knowledge_base",
    "EmbeddingModel": "qwen3-embedding:0.6b",
    "OllamaModel": "qwen3.5:4b",
    "McpUrl": "http://localhost:6174",
    "AiAgentMetaData": [
      {
        "Name": "Paul",
        "SkillPath": "Agents/Skills/paul",
        //"Model": "qwen3.5:4b",
        "Type": "Master",
        "Instructions": "You are a manager"
      },
      {
        "Name": "Linda",
        "SkillPath": "Agents/Skills/linda",
        //"Model": "qwen3.5:9b",
        "instructions": "You provide information about an individuals identity or profession as requested by the user.",
        "Type": "Master",
        "VecStoreMetaData": {
          "Name": "CVs",
          "DisplayName": "CVs",
          "Description": "Contains details information about an individuals identity and proffesional history."
        }
      },
      {
        "Name": "Jimmy",
        "SkillPath": "Agents/Skills/jimmy",
        // "Model": "qwen3.5:9b",
        "Instructions": "You provide advise on finance and accounting as per the user's request'.",
        "Type": "Master",
        "VecStoreMetaData": {
          "Name": "Accounting",
          "DisplayName": "Accounting and finance",
          "Description": "Contains information about accounting and financial management."
        }
      }
    ]
  }
}
 