apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.appName}}
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Values.appName}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{.Values.appName}}
  template:
    metadata:
      labels:
        app: {{.Values.appName}}
    spec:
      containers:
        - name: {{.Values.appName}}
          image: "{{.Values.image.repository}}/{{.Values.appName}}:{{.Values.image.tag}}"
          imagePullPolicy: {{.Values.image.pullPolicy}}
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: agent-storagekey-map
              mountPath: /agent-store-keys/
          env:
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
          envFrom:
            - configMapRef:
                name: {{.Values.appConfigName}}
            - secretRef:
                name: {{.Values.appSecretName}}
        - name: {{.Values.mcpName}}
          image: "{{.Values.image.repository}}/{{.Values.mcpName}}:{{.Values.image.tag}}"
          imagePullPolicy: {{.Values.image.pullPolicy}}
          ports:
            - containerPort: 8082
          volumeMounts:
            - name: agent-storagekey-map
              mountPath: /agent-store-keys/
          env:
            - name: ASPNETCORE_HTTP_PORTS
              value: "8082"
          envFrom:
            - configMapRef:
                name: {{.Values.appConfigName}}
            - secretRef:
                name: {{.Values.appSecretName}}
        - name: ollama
          image: "alpine/ollama:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 11434
          volumeMounts:
            - name: ollama-storage
              mountPath: /root/.ollama
          # resources:
          #   limits:
          #     cpu: 4
          #     memory: 8Gi
          #   requests:
          #     cpu: 2
          #     memory: 4Gi
      volumes:
        - name: ollama-storage
          hostPath:
            path: /var/lib/ollama/ollamamodels # On your physical host machine
            type: DirectoryOrCreate 
        - name:  agent-storagekey-map
          configMap:
            name: {{.Values.agentStoreKeyMapName}}
            items:
              - key: agent-storekey-map.json
                path: agent-storekey-map.json              
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qdrant
  namespace: {{.Values.namespace}}
  labels:
    app: qdrant
spec:
  serviceName: "qdrant" # Must match the Headless Service name above
  replicas: 1
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
        - name: qdrant
          image: "qdrant/qdrant:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6333
              name: http
            - containerPort: 6334
              name: grpc
          # resources:
          #   limits:
          #     cpu: "4"
          #     memory: 4Gi
          #   requests:
          #     cpu: "2"
          #     memory: 2Gi
          volumeMounts:
            - name: qdrant-storage
              mountPath: /qdrant/storage
  # This dynamically creates a dedicated PVC for each replica
  volumeClaimTemplates:
    - metadata:
        name: qdrant-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        # Uncomment and set a storageClassName if you aren't using your cluster's default
        # storageClassName: "standard" 
        resources:
          requests:
            storage: 10Gi
 

