apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.appSecretName}}
  namespace: {{.Values.namespace}}
type: Opaque
stringData:
  ConnectionStrings__Default: "Initial Catalog=zlwtlaut_izybill;Server=148.251.89.211;Trust Server Certificate=True;User ID=zlwtlaut_izybill;Password=01jA9?sg4;"