<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Agents\Skills\acquire-insight\Skill.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="CommunityToolkit.VectorData.Qdrant" />
	<PackageReference Include="DocumentFormat.OpenXml" />
	<PackageReference Include="Microsoft.Agents.AI" />
	  <PackageReference Include="Microsoft.Agents.AI.Harness" />
	  <PackageReference Include="Microsoft.Agents.AI.Workflows" />
	  <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
	  <PackageReference Include="ModelContextProtocol" />
	<PackageReference Include="OllamaSharp" />
	<PackageReference Include="UglyToad.PdfPig" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClientManagement.DataAccessLayer\ClientManagement.DataAccessLayer.csproj" />
    <ProjectReference Include="..\ClientManagement.Models\ClientManagement.Models.csproj" />
  </ItemGroup>

  <ItemGroup>
	  <Content Include="Agents/**/*" CopyToOutputDirectory="Always"></Content>
    <Folder Include="Interfaces\" />
  </ItemGroup>

</Project>
