<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Configurations>Debug;Release;DevOnline</Configurations>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="Microsoft.AspNetCore.Http" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClientManagement.DataAccessLayer\ClientManagement.DataAccessLayer.csproj" />
    <ProjectReference Include="..\ClientManagement.Utils\ClientManagement.Utils.csproj" />
	<PackageReference Include="CommunityToolkit.VectorData.Qdrant" />
	<PackageReference Include="DocumentFormat.OpenXml" />
	<PackageReference Include="UglyToad.PdfPig" />
    <PackageReference Include="OllamaSharp" />
  </ItemGroup>
	<PropertyGroup>
		<NoWarn>$(NoWarn);NU1903</NoWarn>
	</PropertyGroup>
	<ItemGroup>
		<Content Include="Agents/Skills/**/*.md" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>
</Project>
