apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.appConfigName}}
  namespace: {{.Values.namespace}}
data:
  Logging__LogLevel__Default: Information
  Logging__LogLevel__Microsoft.AspNetCore: Warning

  AllowedHosts: "*"
  ApiBaseUrl: "http://{{.Values.appName}}.{{.Values.namespace}}.svc.cluster.local:{{.Values.service.port}}"

  EmailSettings__Smtp: "smtp.gmail.com"
  EmailSettings__SendFrom: "izybill85@gmail.com"
  EmailSettings__Password: "{{.Values.emailPassword}}"
  EmailSettings__Port: "587"

  AppInfo__Version: "0.3.1"
  AppInfo__Name: "IzyBill"
  AppInfo__PoweredBy: "Tsholofelo Given Nkuna"

  Pagination__PageSize: "10"

  AdminAccount__Username: "{{.Values.rootUser}}"
  AdminAccount__Password: "{{.Values.rootPassword}}"

  AI__SkillPath: "Agents/Skills"
  AI__OllamaUrl: "http://localhost:11434"
  AI__VectorStoreUrl: "http://qdrant-0.qdrant.{{.Values.namespace}}.svc.cluster.local:6334"
  AI__VectorStoreCollectionName: "Knowledge_base"
  AI__EmbeddingModel: "qwen3-embedding:0.6b"
  AI__OllamaModel: "qwen3.5:4b"
  AI__McpUrl: "http://localhost:8082"
  AI__AgentStoreKeyMapMountPath: "{{.Values.agentStoreKeyMapMountPath}}/agent-storekey-map.json"
  AI__PhoenixUrl: "http://phoenix-svc.{{.Values.namespace}}.svc.cluster.local:6006/v1/traces"
  AI__AiAgentMetaData__0__Name: "Paul"
  AI__AiAgentMetaData__0__SkillPath: "Agents/Skills/paul"
  AI__AiAgentMetaData__0__Profession: "Manager"
  # AI__AiAgentMetaData__0__Model: "qwen3.5:4b"AgentStoreKeyMapMountPath
  AI__AiAgentMetaData__0__Type: "Master"
  AI__AiAgentMetaData__0__Instructions: "You are a manager"
  AI__AiAgentMetaData__0__VecStoreMetaData__Name: "Reports"
  AI__AiAgentMetaData__0__VecStoreMetaData__DisplayName: "Reports, managed by agent Paul"
  AI__AiAgentMetaData__0__VecStoreMetaData__Description: "Contains information about all progress made by specialist agents."

  AI__AiAgentMetaData__1__Name: "Linda"
  AI__AiAgentMetaData__1__SkillPath: "Agents/Skills/linda"
  AI__AiAgentMetaData__1__Profession: "Billing Specialist"
 # AI__AiAgentMetaData__1__Model: "qwen3.5:9b"
  AI__AiAgentMetaData__1__Instructions: "You are a Billing Specialist. You handle invoice generation, tracking outstanding payments, processing billing disputes, and managing payment terms."
  AI__AiAgentMetaData__1__Type: "Master"
  AI__AiAgentMetaData__1__VecStoreMetaData__Name: "Invoicing"
  AI__AiAgentMetaData__1__VecStoreMetaData__DisplayName: "Invoicing and Billing, managed by agent Sarah"
  AI__AiAgentMetaData__1__VecStoreMetaData__Description: "Contains information about client invoices, payment histories, billing records, and automated payment workflows."

  AI__AiAgentMetaData__2__Name: "Jimmy"
  AI__AiAgentMetaData__2__SkillPath: "Agents/Skills/jimmy"
  AI__AiAgentMetaData__2__Profession: "Revenue & Sales Tracker"
  # AI__AiAgentMetaData__2__Model: "qwen3.5:9b"
  AI__AiAgentMetaData__2__Instructions: "You track received payments and sales performance. You monitor which clients have completed payments, calculate total revenue generated from specific products or services, and provide summaries of business sales trends. You do not generate new invoices."
  AI__AiAgentMetaData__2__Type: "Master"
  AI__AiAgentMetaData__2__VecStoreMetaData__Name: "Revenue_Sales"
  AI__AiAgentMetaData__2__VecStoreMetaData__DisplayName: "Revenue Records and Sales Performance, managed by agent Jimmy"
  AI__AiAgentMetaData__2__VecStoreMetaData__Description: "Contains data on completed invoice payments, revenue breakdowns by client, and sales volume logs for products and services."

