apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.appConfigName}}
  namespace: {{.Values.namespace}}
data:
  Logging__LogLevel__Default: Information
  Logging__LogLevel__Microsoft.AspNetCore: Warning

  AllowedHosts: "*"
  ApiBaseUrl: "http://{{.Values.appName}}.{{.Values.namespace}}.svc.cluster.local:{{.Values.service.port}}"

  EmailSettings__Smtp: "smtp.gmail.com"
  EmailSettings__SendFrom: "izybill85@gmail.com"
  EmailSettings__Password: "{{.Values.emailPassword}}"
  EmailSettings__Port: "587"

  AppInfo__Version: "0.3.1"
  AppInfo__Name: "IzyBill"
  AppInfo__PoweredBy: "Tsholofelo Given Nkuna"

  Pagination__PageSize: "10"

  AdminAccount__Username: "{{.Values.rootUser}}"
  AdminAccount__Password: "{{.Values.rootPassword}}"

  AI__SkillPath: "Agents/Skills"
  AI__OllamaUrl: "http://localhost:11434"
  AI__VectorStoreUrl: "http://qdrant-0.qdrant.{{.Values.namespace}}.svc.cluster.local:6334"
  AI__VectorStoreCollectionName: "Knowledge_base"
  AI__EmbeddingModel: "qwen3-embedding:0.6b"
  AI__OllamaModel: "qwen3.5:4b"
  AI__McpUrl: "http://localhost:8082"
  AI__AgentStoreKeyMapMountPath: "{{.Values.agentStoreKeyMapMountPath}}/agent-storekey-map.json"
  AI__PhoenixUrl: "http://phoenix-svc.{{.Values.namespace}}.svc.cluster.local:6006/v1/traces"

  AI__AiAgentMetaData__0__Name: "Paul"
  AI__AiAgentMetaData__0__SkillPath: "Agents/Skills/paul"
  AI__AiAgentMetaData__0__Profession: "ClientInventorySpecialist"
  # AI__AiAgentMetaData__0__Model: "qwen3.5:4b"
  AI__AiAgentMetaData__0__Instructions: "You specialize in assisting users with client onboarding and product/service catalog configuration. You provide guidance on setup standards and interface with transactional databases via tools to manage client profiles and pricing catalogs. You do not process billing or financial performance analytics."
  AI__AiAgentMetaData__0__Type: "Master"
  AI__AiAgentMetaData__0__VecStoreMetaData__Name: "SystemAdminKnowledge"
  AI__AiAgentMetaData__0__VecStoreMetaData__DisplayName: "Onboarding Procedures and Catalog Management Guides, managed by Paul"
  AI__AiAgentMetaData__0__VecStoreMetaData__Description: "Contains documentation on client onboarding standards, service categorization strategies, system configuration FAQs, and standard pricing guidelines."

  AI__AiAgentMetaData__1__Name: "Linda"
  AI__AiAgentMetaData__1__SkillPath: "Agents/Skills/linda"
  AI__AiAgentMetaData__1__Profession: "BillingSpecialist"
  # AI__AiAgentMetaData__1__Model: "qwen3.5:9b"
  AI__AiAgentMetaData__1__Instructions: "You specialize in invoice generation, draft creation, tracking outstanding payments, and managing billing terms. You leverage transactional data to build bills, adhering to regulatory billing rules. You do not handle base database setup or long-term revenue analysis."
  AI__AiAgentMetaData__1__Type: "Master"
  AI__AiAgentMetaData__1__VecStoreMetaData__Name: "Invoicing_Compliance"
  AI__AiAgentMetaData__1__VecStoreMetaData__DisplayName: "Invoicing Protocols and Compliance Knowledge, managed by Linda"
  AI__AiAgentMetaData__1__VecStoreMetaData__Description: "Contains corporate invoice formatting standards, tax compliance rules, payment term definitions, dispute resolution protocols, and late-fee policies."

  AI__AiAgentMetaData__2__Name: "Jimmy"
  AI__AiAgentMetaData__2__SkillPath: "Agents/Skills/jimmy"
  AI__AiAgentMetaData__2__Profession: "RevenueSalesTracker"
  # AI__AiAgentMetaData__2__Model: "qwen3.5:9b"
  AI__AiAgentMetaData__2__Instructions: "You specialize in tracking received payments and evaluating sales metrics. You provide summaries of business trends and product performance based on finalized revenue records. You do not generate invoices or manage raw client registries."
  AI__AiAgentMetaData__2__Type: "Master"
  AI__AiAgentMetaData__2__VecStoreMetaData__Name: "Revenue_Analysis_Methodology"
  AI__AiAgentMetaData__2__VecStoreMetaData__DisplayName: "Revenue Metrics and Reporting Standards, managed by Jimmy"
  AI__AiAgentMetaData__2__VecStoreMetaData__Description: "Contains framework definitions for sales forecasting, corporate revenue calculation standards, analytical reporting templates, and performance metrics glossaries."

